package com.bwc.model;

public class BwMapBrandEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_map_brand_entity.BRAND_ENTITY_ID
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    private Integer brandEntityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_map_brand_entity.BRAND_ID
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_map_brand_entity.ENTITY_CODE
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    private String entityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_map_brand_entity.SHORT_NAME
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_map_brand_entity.NAME
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_map_brand_entity.ADDRESS
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_map_brand_entity.TELEPHONE
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_map_brand_entity.LNG_X
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    private String lngX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_map_brand_entity.LAT_Y
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    private String latY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_map_brand_entity.LEVEL
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    private String level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_map_brand_entity.BRAND_ENTITY_ID
     *
     * @return the value of bw_map_brand_entity.BRAND_ENTITY_ID
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public Integer getBrandEntityId() {
        return brandEntityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_map_brand_entity.BRAND_ENTITY_ID
     *
     * @param brandEntityId the value for bw_map_brand_entity.BRAND_ENTITY_ID
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public void setBrandEntityId(Integer brandEntityId) {
        this.brandEntityId = brandEntityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_map_brand_entity.BRAND_ID
     *
     * @return the value of bw_map_brand_entity.BRAND_ID
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_map_brand_entity.BRAND_ID
     *
     * @param brandId the value for bw_map_brand_entity.BRAND_ID
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_map_brand_entity.ENTITY_CODE
     *
     * @return the value of bw_map_brand_entity.ENTITY_CODE
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public String getEntityCode() {
        return entityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_map_brand_entity.ENTITY_CODE
     *
     * @param entityCode the value for bw_map_brand_entity.ENTITY_CODE
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_map_brand_entity.SHORT_NAME
     *
     * @return the value of bw_map_brand_entity.SHORT_NAME
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_map_brand_entity.SHORT_NAME
     *
     * @param shortName the value for bw_map_brand_entity.SHORT_NAME
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_map_brand_entity.NAME
     *
     * @return the value of bw_map_brand_entity.NAME
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_map_brand_entity.NAME
     *
     * @param name the value for bw_map_brand_entity.NAME
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_map_brand_entity.ADDRESS
     *
     * @return the value of bw_map_brand_entity.ADDRESS
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_map_brand_entity.ADDRESS
     *
     * @param address the value for bw_map_brand_entity.ADDRESS
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_map_brand_entity.TELEPHONE
     *
     * @return the value of bw_map_brand_entity.TELEPHONE
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_map_brand_entity.TELEPHONE
     *
     * @param telephone the value for bw_map_brand_entity.TELEPHONE
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_map_brand_entity.LNG_X
     *
     * @return the value of bw_map_brand_entity.LNG_X
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public String getLngX() {
        return lngX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_map_brand_entity.LNG_X
     *
     * @param lngX the value for bw_map_brand_entity.LNG_X
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public void setLngX(String lngX) {
        this.lngX = lngX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_map_brand_entity.LAT_Y
     *
     * @return the value of bw_map_brand_entity.LAT_Y
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public String getLatY() {
        return latY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_map_brand_entity.LAT_Y
     *
     * @param latY the value for bw_map_brand_entity.LAT_Y
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public void setLatY(String latY) {
        this.latY = latY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_map_brand_entity.LEVEL
     *
     * @return the value of bw_map_brand_entity.LEVEL
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_map_brand_entity.LEVEL
     *
     * @param level the value for bw_map_brand_entity.LEVEL
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public void setLevel(String level) {
        this.level = level;
    }
}