package com.bwc.model;

public class BwMapBrand {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bw_map_brand.BRAND_ID
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	private Integer brandId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bw_map_brand.BRAND_CODE
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	private String brandCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bw_map_brand.BRAND_NAME
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	private String brandName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bw_map_brand.BRAND_ICON
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	private String brandIcon;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bw_map_brand.BRAND_ID
	 * @return  the value of bw_map_brand.BRAND_ID
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public Integer getBrandId() {
		return brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bw_map_brand.BRAND_ID
	 * @param brandId  the value for bw_map_brand.BRAND_ID
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bw_map_brand.BRAND_CODE
	 * @return  the value of bw_map_brand.BRAND_CODE
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public String getBrandCode() {
		return brandCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bw_map_brand.BRAND_CODE
	 * @param brandCode  the value for bw_map_brand.BRAND_CODE
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public void setBrandCode(String brandCode) {
		this.brandCode = brandCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bw_map_brand.BRAND_NAME
	 * @return  the value of bw_map_brand.BRAND_NAME
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public String getBrandName() {
		return brandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bw_map_brand.BRAND_NAME
	 * @param brandName  the value for bw_map_brand.BRAND_NAME
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bw_map_brand.BRAND_ICON
	 * @return  the value of bw_map_brand.BRAND_ICON
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public String getBrandIcon() {
		return brandIcon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bw_map_brand.BRAND_ICON
	 * @param brandIcon  the value for bw_map_brand.BRAND_ICON
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public void setBrandIcon(String brandIcon) {
		this.brandIcon = brandIcon;
	}
}