package com.bwc.model;

public class BwTbSequence {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_tb_sequence.BS_KEY
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    private String bsKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_tb_sequence.CURRENT_ID
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    private Long currentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_tb_sequence.BS_KEY
     *
     * @return the value of bw_tb_sequence.BS_KEY
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public String getBsKey() {
        return bsKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_tb_sequence.BS_KEY
     *
     * @param bsKey the value for bw_tb_sequence.BS_KEY
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public void setBsKey(String bsKey) {
        this.bsKey = bsKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_tb_sequence.CURRENT_ID
     *
     * @return the value of bw_tb_sequence.CURRENT_ID
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public Long getCurrentId() {
        return currentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_tb_sequence.CURRENT_ID
     *
     * @param currentId the value for bw_tb_sequence.CURRENT_ID
     *
     * @mbggenerated Mon Apr 27 14:46:01 CST 2015
     */
    public void setCurrentId(Long currentId) {
        this.currentId = currentId;
    }
}