package com.bwc.mybatis;

import java.util.ArrayList;
import java.util.List;

public class BwMapBrandExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bw_map_brand
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bw_map_brand
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bw_map_brand
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bw_map_brand
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public BwMapBrandExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bw_map_brand
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bw_map_brand
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bw_map_brand
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bw_map_brand
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bw_map_brand
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bw_map_brand
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bw_map_brand
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bw_map_brand
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bw_map_brand
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bw_map_brand
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bw_map_brand
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andBrandIdIsNull() {
			addCriterion("BRAND_ID is null");
			return (Criteria) this;
		}

		public Criteria andBrandIdIsNotNull() {
			addCriterion("BRAND_ID is not null");
			return (Criteria) this;
		}

		public Criteria andBrandIdEqualTo(Integer value) {
			addCriterion("BRAND_ID =", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotEqualTo(Integer value) {
			addCriterion("BRAND_ID <>", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdGreaterThan(Integer value) {
			addCriterion("BRAND_ID >", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("BRAND_ID >=", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdLessThan(Integer value) {
			addCriterion("BRAND_ID <", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdLessThanOrEqualTo(Integer value) {
			addCriterion("BRAND_ID <=", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdIn(List<Integer> values) {
			addCriterion("BRAND_ID in", values, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotIn(List<Integer> values) {
			addCriterion("BRAND_ID not in", values, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdBetween(Integer value1, Integer value2) {
			addCriterion("BRAND_ID between", value1, value2, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotBetween(Integer value1, Integer value2) {
			addCriterion("BRAND_ID not between", value1, value2, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandCodeIsNull() {
			addCriterion("BRAND_CODE is null");
			return (Criteria) this;
		}

		public Criteria andBrandCodeIsNotNull() {
			addCriterion("BRAND_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andBrandCodeEqualTo(String value) {
			addCriterion("BRAND_CODE =", value, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeNotEqualTo(String value) {
			addCriterion("BRAND_CODE <>", value, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeGreaterThan(String value) {
			addCriterion("BRAND_CODE >", value, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeGreaterThanOrEqualTo(String value) {
			addCriterion("BRAND_CODE >=", value, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeLessThan(String value) {
			addCriterion("BRAND_CODE <", value, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeLessThanOrEqualTo(String value) {
			addCriterion("BRAND_CODE <=", value, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeLike(String value) {
			addCriterion("BRAND_CODE like", value, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeNotLike(String value) {
			addCriterion("BRAND_CODE not like", value, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeIn(List<String> values) {
			addCriterion("BRAND_CODE in", values, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeNotIn(List<String> values) {
			addCriterion("BRAND_CODE not in", values, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeBetween(String value1, String value2) {
			addCriterion("BRAND_CODE between", value1, value2, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeNotBetween(String value1, String value2) {
			addCriterion("BRAND_CODE not between", value1, value2, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandNameIsNull() {
			addCriterion("BRAND_NAME is null");
			return (Criteria) this;
		}

		public Criteria andBrandNameIsNotNull() {
			addCriterion("BRAND_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andBrandNameEqualTo(String value) {
			addCriterion("BRAND_NAME =", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotEqualTo(String value) {
			addCriterion("BRAND_NAME <>", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameGreaterThan(String value) {
			addCriterion("BRAND_NAME >", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameGreaterThanOrEqualTo(String value) {
			addCriterion("BRAND_NAME >=", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLessThan(String value) {
			addCriterion("BRAND_NAME <", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLessThanOrEqualTo(String value) {
			addCriterion("BRAND_NAME <=", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLike(String value) {
			addCriterion("BRAND_NAME like", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotLike(String value) {
			addCriterion("BRAND_NAME not like", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameIn(List<String> values) {
			addCriterion("BRAND_NAME in", values, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotIn(List<String> values) {
			addCriterion("BRAND_NAME not in", values, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameBetween(String value1, String value2) {
			addCriterion("BRAND_NAME between", value1, value2, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotBetween(String value1, String value2) {
			addCriterion("BRAND_NAME not between", value1, value2, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandIconIsNull() {
			addCriterion("BRAND_ICON is null");
			return (Criteria) this;
		}

		public Criteria andBrandIconIsNotNull() {
			addCriterion("BRAND_ICON is not null");
			return (Criteria) this;
		}

		public Criteria andBrandIconEqualTo(String value) {
			addCriterion("BRAND_ICON =", value, "brandIcon");
			return (Criteria) this;
		}

		public Criteria andBrandIconNotEqualTo(String value) {
			addCriterion("BRAND_ICON <>", value, "brandIcon");
			return (Criteria) this;
		}

		public Criteria andBrandIconGreaterThan(String value) {
			addCriterion("BRAND_ICON >", value, "brandIcon");
			return (Criteria) this;
		}

		public Criteria andBrandIconGreaterThanOrEqualTo(String value) {
			addCriterion("BRAND_ICON >=", value, "brandIcon");
			return (Criteria) this;
		}

		public Criteria andBrandIconLessThan(String value) {
			addCriterion("BRAND_ICON <", value, "brandIcon");
			return (Criteria) this;
		}

		public Criteria andBrandIconLessThanOrEqualTo(String value) {
			addCriterion("BRAND_ICON <=", value, "brandIcon");
			return (Criteria) this;
		}

		public Criteria andBrandIconLike(String value) {
			addCriterion("BRAND_ICON like", value, "brandIcon");
			return (Criteria) this;
		}

		public Criteria andBrandIconNotLike(String value) {
			addCriterion("BRAND_ICON not like", value, "brandIcon");
			return (Criteria) this;
		}

		public Criteria andBrandIconIn(List<String> values) {
			addCriterion("BRAND_ICON in", values, "brandIcon");
			return (Criteria) this;
		}

		public Criteria andBrandIconNotIn(List<String> values) {
			addCriterion("BRAND_ICON not in", values, "brandIcon");
			return (Criteria) this;
		}

		public Criteria andBrandIconBetween(String value1, String value2) {
			addCriterion("BRAND_ICON between", value1, value2, "brandIcon");
			return (Criteria) this;
		}

		public Criteria andBrandIconNotBetween(String value1, String value2) {
			addCriterion("BRAND_ICON not between", value1, value2, "brandIcon");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bw_map_brand
	 * @mbggenerated  Tue Apr 28 11:37:00 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bw_map_brand
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 28 11:36:16 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}